apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiiduf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiiduf
  template:
    metadata:
      labels:
        app: shiiduf
    spec:
      containers:
      - image: okteto.dev/shiiduf:latest
        name: shiiduf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2072f25d-dd9e-48e8-bb3e-c6b9c21b0241"
        - name: Vless_Path
          value: "/vl5bbff55"
        - name: Vmess_UUID
          value: "2072f25d-dd9e-48e8-bb3e-c6b9c21b0241"
        - name: Vmess_Path
          value: "/vmhrrt666"
        - name: Share_Path
          value: "/v2link"
